import {model,base,contracted,assumptions as a,usd,pct,serviceLines} from './financial-model.mjs';
export const currentSources={
 'model-v6.1':{title:'SmartTec B300 Investor Model v6.1 · independently recalculated in native Excel · SHA-256 '+model.source.sha256},
 'owner-record':{title:'Management statements supplied during project diligence; underlying agreements and funds not independently verified'},
 'campus-record':{title:'Supplied boundary survey and owner-provided current parcel and building information'}
};
const fact=(id,question,answer,status='Model assumption; not a commitment',sourceIds=['model-v6.1'])=>({id,question,answer,status,sourceIds,reviewedAt:model.reviewedAt});
export const currentInvestmentFacts=[
 fact('F01','What is SmartTec developing?','SmartTec is developing a proposed 64-B300 campus deployment on the 39.39-acre Mead, Oklahoma property. The reviewed v6.1 financial baseline assumes eight complete Supermicro systems together in one building and air cooling. The newer campus study illustrates four systems in A, four in C and direct liquid cooling; that scope has not been priced into v6.1. Grid power is planned at launch. Equipment is not commissioned inventory; manufacturing, solar and BESS have separate future scopes.','Development stage',['model-v6.1','owner-record','campus-record']),
 fact('F-services','What services do shared inference, dedicated servers and colocation provide?',serviceLines.map(s=>s.name+': '+s.tenancy+'; '+s.ownership+'. '+s.description).join(' ')),
 fact('F11','What is Phase 1 GPU capacity?',`${base.capacity.nodes} proposed eight-GPU systems: ${base.capacity.installedGpus} installed GPUs in the purchase model, ${base.capacity.saleableGpus} saleable and ${base.capacity.heldBackGpus} held back. Four held-back GPUs are a financial allocation, not a spare eight-GPU node or proven failover. Dedicated full-node bookings and shared GPU capacity must fit the same fleet; revenue cannot be counted twice.`),
 fact('F07','How much cooling is installed?','The earlier v6.1 selected-building report records no working air conditioning; cooling must be newly supplied and commissioned. That financial baseline budgets two nominal 50-ton chillers and five 40-kW in-row units, including spare units. These are planning quantities, not installed equipment, an engineered approval or a guaranteed availability level. The newer direct-liquid A/C campus concept requires repricing; its all-new cooling design pending final engineering is not established by those allowances.','Owner report plus preliminary model',['model-v6.1','owner-record']),
 fact('F17','How much funding is required?',`The base initial funding model is ${usd(base.capital.totalUsd)}: ${usd(base.capital.hardwareUsd)} hardware including shared storage/spares and freight/tax, ${usd(base.capital.infrastructureUsd)} infrastructure, and ${usd(base.capital.cashReserveUsd)} working cash. The full-60-GPU $7.50/60-month contract scenario requires ${usd(contracted.capital.totalUsd)} because the modeled reserve changes. Against the owner-reported $6m, base overage is ${usd(base.capital.founderFundingGapUsd)}. These are complete modeled categories, not firm installed quotations or a fixed outside-investor raise.`),
 fact('F19','What ROI will an investor receive?',`No investor-specific return is agreed. The base five-year dated funded project IRR is ${pct(base.returns.datedFundedIrr)}. A hypothetical full-60-GPU contract at $7.50 for 60 months, 95% paid share and a six-year hold gives ${pct(contracted.returns.datedFundedIrr)}. Both are unlevered modeled project cash returns including taxes, the modeled BC LLC payment, reserve policy and resale. Contracts, costs, funding and investor rights still need documentation.`),
 fact('F-revenue-math','What revenue does the B300 model generate at $6.50 per GPU-hour?',`The base starts at $6.50 per B300 GPU-hour, 55% paid utilization in Year 1 and 70% thereafter, with a 10% annual price decline. Six months of construction leave six operating months in Year 1: gross revenue ${usd(base.annual[0].revenueUsd)}. Year 2 gross revenue is ${usd(base.annual[1].revenueUsd)}. Gross billing is not collected cash or profit. The contracted scenarios instead require 95% paid share on the contracted GPUs; that is 22.8 paid hours per day, not observed utilization.`),
 fact('F-power','What is the power cost and energy strategy?',`Grid at launch: ${rateCents(a.energyUsdPerKwh)} cents per kWh plus ${usd(a.demandUsdPerKwMonth)} per billed peak kW per month in the model, with 3% cost inflation. No signed utility tariff or commissioned firm capacity is established. Solar and BESS are a separate future investment. Behind-the-meter savings are excluded.`),
 fact('F-costs','Which expenses are included?',`Electricity, demand charges, channel fees, network, staffing, insurance, other operating costs, support, modeled income tax and the BC LLC profit payment are included. Merchant channel fees blend to ${pct(a.blendedMerchantCommission,1)}; contracted fees are ${pct(a.contractCommission,0)}. Support is assumed included for ${a.includedSupportMonths} months from first billing and then charged at ${pct(a.postWarrantySupportRate,0)} of B300 system purchase cost annually before escalation. The Phase-1 internet allowance is $4,000/month; bandwidth, carrier scope and actual cost require reconciliation. Supplier terms require confirmation.`),
 fact('F-cash','Does the cash reserve guarantee enough liquidity?',`${a.cashReserveMonths} months of modeled cost reserve plus receivables are funded at inception. The retained-cash target is a distribution policy, not an enforced minimum; launch losses can reduce it. The model uses annual distributions and a separately dated final receivable, not a full monthly life-of-project liquidity test. Net-${a.collectionDays} collection and no customer default are assumptions.`),
 fact('F-exit','Are the equipment resale values guaranteed?',`No. The model assumes ${pct(a.hardwareResaleYear5,0)} hardware resale in Year 5 or ${pct(a.hardwareResaleYear6,0)} in Year 6 and ${pct(a.infrastructureResale,0)} infrastructure recovery. Those are unverified exit assumptions, with modeled sale tax. Operating-only results exclude terminal recovery. No renewal is assumed; expired contracts revert to merchant pricing and utilization.`),
 fact('F-site','Who owns the site and what does BC LLC receive?','BC LLC, associated with the CEO, is the landowner. Management reports the property is paid off and both parties signed a 50-year commitment. The annual 1% payment is described as profit after expenses; the model uses positive after-tax accounting income. The signed document, accounting definition, related-party terms and investor rights need legal review. SmartTec does not thereby own the land.','Owner reported; legal verification pending',['owner-record','model-v6.1']),
 fact('F-date','When will the GPU service launch?','After procurement, utility and cooling readiness, commissioning and customer acceptance. Six build months are a modeling assumption. The workbook date 1 January 2027 is a placeholder for dated-return calculations, not an announced construction or customer-service date.'),
 fact('F-scale','Does a larger GPU fleet automatically improve returns?','No. The maximum-size base scenario is a separate hypothetical 240-installed / 225-saleable-GPU study, not an approved expansion. Its dated project IRR remains below the 15% model hurdle. Expansion requires additional funding, customer commitments, utility capacity and engineering; scale alone does not establish profitability.')
];
function rateCents(value){return (value*100).toFixed(1);}
