import {investmentReadiness as r} from './investment-readiness.mjs';

const usd=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);
const full=r.cooling.cases.find(item=>item.id==='full-scope');
const lower=r.cooling.cases.find(item=>item.id==='lower-cost');
const fact=(id,question,answer,status='owner-reported; verification pending',sourceIds=['current-owner-update','current-readiness'])=>({id,question,answer,status,sourceIds,reviewedAt:r.reviewedAt});

// Current monetary answers read the same inputs as the page and PDF exporter.
// Historical qualitative records remain in knowledge_base.json.
export const currentInvestmentFacts=[
  fact('F01','What is SmartTec developing?',`SmartTec.dev LLC, under SmartTec Holdings LLC, proposes ${r.hardware.installedGPUs} B300 GPUs in ${r.hardware.systems} complete ${r.hardware.supplier} systems in one building on a 39.39-acre Mead, Oklahoma campus. Parent Z1Power's battery-production background informs the broader strategy. The initial fleet is proposed, not commissioned inventory. Manufacturing, solar and storage development have separate scopes.`),
  fact('F11','What is Phase 1 compute?',`${r.hardware.systems} complete liquid-cooled ${r.hardware.supplier} systems, each with ${r.hardware.gpusPerSystem} B300 GPUs, at the owner-reported ${usd(r.hardware.systemPrice)} per system. Hardware totals ${usd(r.hardware.totalCost)}. The plan allocates ${r.hardware.saleableGPUs} saleable GPUs and ${r.hardware.reserveGPUs} financial reserves. The earlier RTX/B300 starter mix is historical. ${r.hardware.verification}`),
  fact('F14','Is B300 included in Phase 1?',`The current proposed first deployment is B300-focused: ${r.hardware.installedGPUs} GPUs in ${r.hardware.systems} complete ${r.hardware.supplier} systems. ${r.hardware.reserveNote} The DGX B300 imagery is a visual reference, not the selected Supermicro configuration or installed SmartTec equipment.`),
  fact('F07','How much cooling is installed?',`The owner confirms that the one building selected for the first ${r.hardware.installedGPUs} B300 GPUs has no working air conditioning. All liquid, residual-air and ancillary cooling must be newly supplied and commissioned. Earlier nominal cooling schedules elsewhere on the property do not establish usable capacity for this deployment.`),
  fact('F-cooling-cost','What will cooling cost, and can we use refurbished chillers?',`The ${usd(full.installedCoolingAllowance)} full-scope cooling benchmark is an analyst allowance, not minimum pricing or a supplier bid. A ${usd(lower.installedCoolingAllowance)} sensitivity assumes a $100,000 chiller pair and deferred separate dry coolers, retaining other allowances and 20% contingency. That is not a verified refurbished quotation. Management permits used/refurbished equipment and is seeking the lowest complete installed proposal meeting the agreed service requirements. All new room cooling remains in scope.`, 'planning comparison; quotes pending'),
  fact('F-cooling-load','How much thermal capacity does the initial cooling plan need?',`The conservative shared-plant screen is ${r.cooling.screeningDutyPerChillerKW} kW net duty per full-duty chiller. ${r.cooling.screeningBasis} Final capacity, component redundancy, fluid temperatures and the room-cooling arrangement depend on OEM requirements and engineering. Installed capacity is not the same as actual operating load.`, 'engineering screening assumption'),
  fact('F-contractors','Who will install the cooling and electrical systems?','The owner confirms a mechanical contractor, electrician and plumber are available through the team. Their complete prices, scopes and B300-specific design review remain to be established. The proposed quote process coordinates OEM requirements, equipment, piping, electrical work, controls, commissioning and service without treating contractor availability as free or prepaid installation.'),
  fact('F17','How much funding is required?',`A complete funding requirement and final outside-investor raise are not established. The hardware is ${usd(r.hardware.totalCost)}. Retaining ${usd(r.budget.startupAllowance)} startup/acquisition and ${usd(r.budget.openingReserve)} opening reserve gives partial initial funding of ${usd(full.partialInitialFunding)} with the full-scope cooling comparison, or ${usd(lower.partialInitialFunding)} with the lower-cost sensitivity. Both exclude unknown non-cooling site work, reserve revisions and later cash calls. Match overlapping scopes before deductions. The old ${usd(r.budget.oldCombinedSiteAllowance)} combined site allowance must be replaced, not added unchanged.`, 'partial budget; complete funding unresolved'),
  fact('F-founder-funding','Will the founders cover the amount above six million dollars?',`Management reports ${usd(r.founderCapital.initialAvailable)} initially available and willingness to personally cover the overage. The partial comparisons imply ${usd(full.additionalFounderContribution)} or ${usd(lower.additionalFounderContribution)} above that initial amount, before unresolved site work and other adjustments. These are indicated additional founder contributions, not a fixed outside-investor funding gap. Additional availability, timing, legal form and transfers remain unverified.`),
  fact('F18','Who owns the property and is it investor collateral?',`Management identifies ${r.property.ownerReportedLandholder}, associated with the CEO, as the landholder and reports the property paid off with existing buildings. A ${r.property.siteAgreementYears}-year agreement with SmartTec is signed by both parties, owner-confirmed. The agreement and title have not been reviewed. Do not treat the land as owned by SmartTec, contributed cash or investor collateral without the relevant rights and documents.`),
  fact('F-site-payment','What does SmartTec pay BC LLC for the site?',`${r.property.paymentBasis} Both parties' signatures and the ${r.property.siteAgreementYears}-year term are owner-confirmed. The written accounting definition, other site obligations, related-party rights and treatment of taxes, capital expenditure, financing and losses need review. The BC LLC payment is not yet calculated in the project model.`),
  fact('F22','Are customer contracts signed?',`${r.commercial.status} No binding minimum-payment receipts are established. A reported potential request for a larger fleet and a prospective buyer's resale claims remain commercial discussions, not orders or contracted revenue. Agree the paying entity, workload, quantity, net pricing, minimum payments, acceptance, duration and cancellation before booking revenue.`),
  fact('F-revenue-math','What revenue could sixty GPUs generate at $6.50 per hour?',`At the illustrative ${r.commercial.illustrativePaidHoursPerDay} paid hours per saleable GPU per day, ${r.hardware.saleableGPUs} GPUs at $${r.commercial.proposedGrossRatePerGPUHour.toFixed(2)} for ${r.commercial.daysPerYear} days produce ${usd(r.commercial.grossAnnualAtIllustrativePaidHours)} in annual gross billing arithmetic. This is not contracted revenue, collected cash or profit. Platform fees, collection, utilization, service obligations and all operating/capital costs remain separate.`, 'uncontracted revenue arithmetic'),
  fact('F19','What ROI will I receive?',`An updated project ROI, payback and final investor return are not established. ${r.decision} The editable calculator gives conditional results for entered assumptions. Its optional pro-rata investor view does not establish agreed investor rights.`, 'current return unresolved'),
  fact('F-economics-2026','Is SmartTec profitable, and should we add more RTX, B200 or B300 GPUs?',`Profitability is not yet established for the updated deployment. ${r.historicalModel.basis} The earlier 72-GPU mathematical threshold is not a current recommendation. Complete costs and contracted customer terms must support any purchase or expansion; founder willingness to fund costs does not itself improve the return.`, 'historical comparison superseded by new cost review'),
  fact('F27','What makes this project different?',`The proposed case combines founder funding, a reported ${r.property.siteAgreementYears}-year site agreement on a 39.39-acre campus, a ${r.hardware.installedGPUs}-B300 first deployment and a solar/battery/gas supply strategy. These management reports need documented rights, complete costs and customer commitments to support an investment. The power advantage is not yet an independently verified all-in delivered price.`),
  fact('F-power-agreement','Does SmartTec have behind-the-meter power and an energy agreement?',`${r.power.basis} No exclusive continuous kW, verified operating date or confirmed all-in tariff is established here. Historical 7-cent calculator sensitivities show a price change only; they do not prove available power or include unspecified generation obligations.`),
];
