import {model,base,contracted,maximum,assumptions as a,headlineIrr,usd,pct,rate,serviceLines} from './financial-model.mjs';

export const currentSources={
 'model-v6.1.1':{title:`${model.source.filename} · reviewed source SHA-256 ${model.source.sha256}`},
 'owner-record':{title:'Management statements supplied during project diligence; underlying agreements and funds not independently verified'},
 'campus-record':{title:'Supplied boundary survey and owner-provided current parcel and building information'}
};
const fact=(id,question,answer,status='Model assumption; not a commitment',sourceIds=['model-v6.1.1'])=>({id,question,answer,status,sourceIds,reviewedAt:model.reviewedAt});
const rateCents=value=>(value*100).toFixed(1);
const baseOperatingCashLine=base.annual.map(year=>`Year ${year.year} ${usd(year.operatingCashUsd)}`).join(', ');
const baseHasPositiveAnnualOperatingCash=base.annual.every(year=>year.operatingCashUsd>0);
const paidHoursPerDay=(24*contracted.commercial.contractPaidShare).toFixed(1);
const contractedMerchantGpus=contracted.capacity.saleableGpus-contracted.commercial.contractedGpus;

export const currentInvestmentFacts=[
 fact('F01','What is SmartTec developing?',`SmartTec is developing a proposed ${base.capacity.installedGpus}-B300 campus deployment on the 39.39-acre Mead, Oklahoma property. The reviewed financial baseline assumes ${base.capacity.nodes} complete Supermicro systems together in one building with its original air-cooled server scope. The newer campus study illustrates four systems in Building A, four in Building C and direct liquid cooling; that scope has not been priced into the workbook baseline. Grid power is planned at launch. Equipment is not commissioned inventory; manufacturing, solar and BESS have separate future scopes.`,'Development stage',['model-v6.1.1','owner-record','campus-record']),
 fact('F-services','What services do shared inference, dedicated servers and colocation provide?',serviceLines.map(s=>s.name+': '+s.tenancy+'; '+s.ownership+'. '+s.description).join(' ')),
 fact('F11','What is Phase 1 GPU capacity?',`${base.capacity.nodes} proposed eight-GPU systems: ${base.capacity.installedGpus} installed GPUs in the purchase model, ${base.capacity.saleableGpus} saleable and ${base.capacity.heldBackGpus} held back. The ${base.capacity.heldBackGpus} held-back GPUs are a financial allocation, not a spare eight-GPU node or proven failover. Dedicated full-node bookings and shared GPU capacity must fit the same fleet; revenue cannot be counted twice.`),
 fact('F07','How much cooling is installed?',`The selected-building report records no working air conditioning; cooling must be newly supplied and commissioned. The financial baseline budgets ${base.technical.chillerCount} nominal ${base.technical.chillerUnitTons}-ton chillers and ${base.technical.inRowCoolerCount} ${base.technical.inRowUnitKw}-kW in-row units, including spare units. These are planning quantities, not installed equipment, an engineered approval or a guaranteed availability level. The newer direct-liquid Buildings A/C campus concept requires repricing; its all-new cooling design is not established by those allowances.`,'Owner report plus preliminary model',['model-v6.1.1','owner-record']),
 fact('F17','How much funding is required?',`The Base initial funding model is ${usd(base.capital.totalUsd)}: ${usd(base.capital.hardwareUsd)} hardware including shared storage/spares and freight/tax, ${usd(base.capital.infrastructureUsd)} infrastructure, and ${usd(base.capital.cashReserveUsd)} working cash. The unsigned workbook contract comparison—${contracted.commercial.contractedGpus} reserved GPUs at ${rate(contracted.commercial.contractRateUsd)} per GPU-hour, ${pct(contracted.commercial.contractPaidShare,0)} paid share and ${contracted.commercial.contractTermMonths} months, plus ${contractedMerchantGpus} merchant GPUs—requires ${usd(contracted.capital.totalUsd)}. Against the owner-reported $6m, Base overage is ${usd(base.capital.founderFundingGapUsd)}. These are modeled categories, not firm installed quotations or a fixed outside-investor raise.`),
 fact('F19','What ROI will an investor receive?',`No investor-specific return is agreed. The workbook uses headline project IRR as its primary return metric. The Base records ${baseHasPositiveAnnualOperatingCash?'positive':'mixed'} annual operating cash (${baseOperatingCashLine}) after the initial ${usd(base.capital.totalUsd)} funding requirement. Its ${base.horizonYears}-year headline project IRR is ${pct(headlineIrr(base))} against a ${pct(a.hurdleRate,0)} hurdle, with ${base.returns.moic.toFixed(2)}× MOIC including assumed resale and ${usd(base.returns.unrecoveredOperatingCapitalUsd)} unrecovered from operations. Positive annual operations do not establish full recovery of the initial investment. The unsigned Contracted scenario combines ${contracted.commercial.contractedGpus} reserved GPUs at ${rate(contracted.commercial.contractRateUsd)} for ${contracted.commercial.contractTermMonths} months with ${contractedMerchantGpus} merchant GPUs; its headline IRR is ${pct(headlineIrr(contracted))}. Annual-funded and dated-funded returns remain cash-timing diagnostics, not the headline result or a promised investor return.`),
 fact('F-revenue-math',`What revenue does the B300 model generate at ${rate(base.commercial.merchantRateYear1Usd)} per GPU-hour?`,`The Base starts at ${rate(base.commercial.merchantRateYear1Usd)} per B300 GPU-hour, ${pct(base.commercial.merchantUtilizationYear1,0)} paid utilization in Year 1 and ${pct(base.commercial.merchantUtilizationYear2Plus,0)} thereafter, with a ${pct(Math.abs(base.commercial.annualMerchantRateChange),0)} annual price decline. ${base.commercial.buildMonths} months of construction leave ${12-base.commercial.buildMonths} operating months in Year 1: gross revenue ${usd(base.annual[0].revenueUsd)}. Year 2 gross revenue is ${usd(base.annual[1].revenueUsd)}. Gross billing is not collected cash or profit. The unsigned Contracted comparison applies ${pct(contracted.commercial.contractPaidShare,0)} paid share to ${contracted.commercial.contractedGpus} GPUs at ${rate(contracted.commercial.contractRateUsd)} for ${contracted.commercial.contractTermMonths} months—${paidHoursPerDay} paid hours per day, a minimum-payment assumption rather than observed utilization. The other ${contractedMerchantGpus} saleable GPUs follow that scenario's merchant inputs.`),
 fact('F-power','What is the power cost and energy strategy?',`Grid at launch: ${rateCents(a.energyUsdPerKwh)} cents per kWh plus ${usd(a.demandUsdPerKwMonth)} per billed peak kW per month in the model, with ${pct(a.annualCostInflation,0)} cost inflation. No signed utility tariff or commissioned firm capacity is established. Solar and BESS are a separate future investment. Behind-the-meter savings are excluded.`),
 fact('F-costs','Which expenses are included?',`Electricity, demand charges, channel fees, network, staffing, insurance, other operating costs, support, modeled income tax and the BC LLC profit payment are included. Merchant channel fees blend to ${pct(a.blendedMerchantCommission,1)}; contracted fees are ${pct(a.contractCommission,0)}. Support is assumed included for ${a.includedSupportMonths} months from first billing and then charged at ${pct(a.postWarrantySupportRate,0)} of B300 system purchase cost annually before escalation. The Phase-1 internet allowance is ${usd(a.phase1InternetAnnualUsd/12)}/month; bandwidth, carrier scope and actual cost require reconciliation. Supplier terms require confirmation.`),
 fact('F-cash','Does the cash reserve guarantee enough liquidity?',`${a.cashReserveMonths} months of modeled cost reserve plus receivables are funded at inception. The retained-cash target is a distribution policy, not an enforced minimum; launch losses can reduce it. Headline IRR uses the workbook's annual project cash series. Annual-funded and dated-funded returns are separate distribution and timing diagnostics, and the model is not a full monthly life-of-project liquidity test. Net-${a.collectionDays} collection and no customer default are assumptions.`),
 fact('F-exit','Are the equipment resale values guaranteed?',`No. The model assumes ${pct(a.hardwareResaleYear5,0)} hardware resale in Year 5 or ${pct(a.hardwareResaleYear6,0)} in Year 6 and ${pct(a.infrastructureResale,0)} infrastructure recovery. Those are unverified exit assumptions, with modeled sale tax. Operating-only results exclude terminal recovery. No renewal is assumed; expired contracts revert to merchant pricing and utilization.`),
 fact('F-site','Who owns the site and what does BC LLC receive?','BC LLC, associated with the CEO, is the landowner. Management reports the property is paid off and both parties signed a 50-year commitment. The annual 1% payment is described as profit after expenses; the model uses positive after-tax accounting income. The signed document, accounting definition, related-party terms and investor rights need legal review. SmartTec does not thereby own the land.','Owner reported; legal verification pending',['owner-record','model-v6.1.1']),
 fact('F-date','When will the GPU service launch?',`After procurement, utility and cooling readiness, commissioning and customer acceptance. ${base.commercial.buildMonths} build months are a modeling assumption. The workbook date ${new Date(a.modelStartDate+'T00:00:00Z').toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'})} is a placeholder for return calculations, not an announced construction or customer-service date.`),
 fact('F-scale','Does a larger GPU fleet automatically improve returns?',`Management reports an infrastructure design target of up to 240 B300 GPUs: 30 systems, with 225 saleable and 15 held back in the workbook sensitivity. The initial phase is eight systems / 64 installed / 60 saleable; reaching the target adds 22 systems / 176 GPUs. This is not commissioned or independently approved capacity. The maximum-size Base scenario is a separate hypothetical ${maximum.capacity.installedGpus}-installed / ${maximum.capacity.saleableGpus}-saleable-GPU study, not an approved expansion. Its headline project IRR is ${pct(headlineIrr(maximum))}, below the ${pct(a.hurdleRate,0)} model hurdle. Expansion requires additional funding, customer commitments, utility capacity and engineering; scale alone does not establish an investable return.`)
];
